services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # auto-register all commands as services
    Basilicom\ImportDataValidator\Command\:
        resource: '../../Command'
        public: true
        tags: ['console.command']

    Basilicom\ImportDataValidator\Validator\Result\ValidationResultFactory: ~
    Basilicom\ImportDataValidator\Validator\Result\ValidationErrorFactory: ~

    sample.rules.dataset-count:
      class: Basilicom\ImportDataValidator\Rules\DatasetCountRule
      arguments:
        $countHeadline: false
        $min: 5
        $max: 10

    sample.rules.existing-columns:
      class: Basilicom\ImportDataValidator\Rules\ExistingColumnsRule
      arguments:
        $columnNames:
          - 'SKU'
          - 'Title'
          - 'Description'
          - 'Barcode'
          - 'Size'
          - 'Price'

    sample.rules.regex.sizes:
      class: Basilicom\ImportDataValidator\Rules\RegexRule
      arguments:
        $canBeEmpty: true
        $columnNames:
          - 'Size'
        $regex: '^(XS|S|M|L|XL|XXL)$'

    sample.rules.regex.sku:
      class: Basilicom\ImportDataValidator\Rules\RegexRule
      arguments:
        $canBeEmpty: false
        $columnNames:
          - 'SKU'
        $regex: '^\d{3}$'

    sample.ruleset:
      class: Basilicom\ImportDataValidator\Validator\DefaultRuleSet
      public: true
      arguments:
        $rules:
          - '@sample.rules.dataset-count'
          - '@sample.rules.existing-columns'
          - '@sample.rules.regex.sizes'
          - '@sample.rules.regex.sku'

    sample.validator.csv:
      class: Basilicom\ImportDataValidator\Validator\DefaultCsvValidator
      public: true
      arguments:
        $separator: ';'

    sample.validator.xlsx:
      class: Basilicom\ImportDataValidator\Validator\DefaultXlsxValidator
      public: true
      arguments:
        $csvValidator: '@sample.validator.csv'
        $datasheetName: 'Sheet 1'

